spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/INVENTORY
    username: postgres
    password: david12345

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  output:
    ansi:
      enabled: ALWAYS